kind: pipeline
type: exec
name: test-windows

trigger:
  branch:
    exclude:  # special branches
    - packaging
    - pip
    - conda
    - docs
    - deploy-pip
    - deploy-conda
    - deploy-docs
    - release
    - app

platform:
  os: windows

steps:
- name: install
  commands:
  - C:\Windows\System32\cleanmgr.exe /dC
  - Remove-Item -Recurse -Force -ErrorAction Ignore C:\\Users\\IEUser\\miniconda3\\Lib\\site-packages\\pyrocko
  # 2024-01-02, python downgrade required because vtk package not available yet for 3.12:
  - conda create --name test_env_${DRONE_BUILD_NUMBER} --yes python=3.11 pytest
  - conda run --no-capture-output --name test_env_${DRONE_BUILD_NUMBER} python install.py deps conda --yes
  - conda run --no-capture-output --name test_env_${DRONE_BUILD_NUMBER} python install.py user --yes
  - New-Item -Path test\\data -ItemType SymbolicLink -Value C:\\vagrant\\test-data
  # ensure config is there to prevent race conditions in parallel test runs
  - conda run --no-capture-output --name test_env_${DRONE_BUILD_NUMBER} python -m pyrocko.config
  - echo "installation is done"

- name: test-base
  commands:
  - conda run --no-capture-output --name test_env_${DRONE_BUILD_NUMBER} python -m pytest -v test/base
  depends_on:
  - install

- name: test-gf
  commands:
  - conda run --no-capture-output --name test_env_${DRONE_BUILD_NUMBER} python -m pytest -v test/gf
  depends_on:
  - install

- name: test-examples
  commands:
  - mkdir test\\example_run_dir
  - mkdir test\\example_run_dir_local
  - New-Item -Path test\\example_run_dir\\ak135_static -ItemType SymbolicLink -Value C:\\vagrant\\test-data\\gf_stores\\ak135_static
  - New-Item -Path test\\example_run_dir\\crust2_mf -ItemType SymbolicLink -Value C:\\vagrant\\test-data\\gf_stores\\crust2_mf
  - New-Item -Path test\\example_run_dir\\gf_abruzzo_nearfield_vmod_Ameri -ItemType SymbolicLink -Value C:\\vagrant\\test-data\\gf_stores\\gf_abruzzo_nearfield_vmod_Ameri
  - New-Item -Path test\\example_run_dir\\iceland_reg_v2 -ItemType SymbolicLink -Value C:\\vagrant\\test-data\\gf_stores\\iceland_reg_v2
  - conda run --no-capture-output --name test_env_${DRONE_BUILD_NUMBER} python -m pytest -v test/examples
  depends_on:
  - install

- name: test-gui
  commands:
  - conda run --no-capture-output --name test_env_${DRONE_BUILD_NUMBER} python -m pytest -v test/gui/test_snuffler.py
  depends_on:
  - install

- name: finalize
  commands: []
  depends_on:
  - test-base
  - test-gf
  - test-examples
  - test-gui

- name: cleanup
  commands:
  - conda env remove --name test_env_${DRONE_BUILD_NUMBER} --yes
  depends_on:
  - finalize
  when:
    status:
    - failure
    - success
