language: python

cache:
    pip: true
    directories:
      - $TRAVIS_BUILD_DIR/pyrocko/test/data

env:
  global:
      - OMP_NUM_THREADS=2

matrix:
  include:
    - os: linux
      python: 2.7
      virtualenv:
          system_site_packages: true
      dist: precise
#        - os: osx
#          osx_image: xcode7.3
#          language: generic
#    allow_failures:
#        - os: osx
#
addons:
  apt:
    packages: [ python-qt4, python-qt4-gl, python-qt4-dev, python-dev,
          gfortran, libatlas-dev, libopenblas-dev,
          python-yaml, python-tk, libyaml-dev,
          poppler-utils, ghostscript, imagemagick, xvfb,
          libssl1.0.0 ]

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink libyaml; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc libyaml; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install matplotlib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcode-select --install || true ; fi
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib scipy numpy matplotlib
  - pip install progressbar setuptools flake8 pyyaml coveralls jinja2 future coverage nose

  - git clone https://github.com/pyrocko/fomosto-qseis
  - cd fomosto-qseis; autoreconf -i; ./configure; make; export PATH=$PATH:`pwd`/src; cd ..

  - git clone https://github.com/pyrocko/fomosto-qseis2d
  - cd fomosto-qseis2d; autoreconf -i; ./configure; make; export PATH=$PATH:`pwd`/src/r:`pwd`/src/s; cd ..

  - git clone https://github.com/pyrocko/fomosto-psgrn-pscmp
  - cd fomosto-psgrn-pscmp; autoreconf -i; ./configure; make; export PATH=$PATH:`pwd`/src/psgrn:`pwd`/src/pscmp; cd ..

  - git clone https://github.com/pyrocko/fomosto-qssp.git
  - cd fomosto-qssp; autoreconf -i; ./configure; make; export PATH=$PATH:`pwd`/src; cd ..

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then flake8 src/ test/ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3 ; fi

install:
  - pip install .

script:
  - travis_wait nosetests run --with-coverage --cover-package=pyrocko test/

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls; fi


deploy:
  - provider: pypi
    user: pyrocko
    password: 
      secure: "crUt0q8F1oSgG5nzfpjd8bmBtHpVWXZE/qYVRlniux4X7tkO6GnW1rZpE2iBJxjEd3ADmgGZwFKj5215HHOZlcxFVQ/w8BnpI9WCkEaph0kA1I+aIrZg+fzpyEcskQ5Nzg1YQIcN/5wVEwmSZtK55gZyFccZMjqZQTkMJiJHZUGT1SyMYlFtoZ508lXtRxhC1EqhBSUa67KIaZoyA1BTgNEFzRNHCqquyb0dalbaiMfpl3UVxzPkik+L9yIUUc/xKC5NRWwAJY6xT7Qf+lvTC1MTSaNva0TG4PpZ5Zfr/N9HuJXXNTToRAd39tSSypt6TeIvOKA7caD6QNWzioQwA86mjskR1GgRTYo1yEAJApBbHtRWvZvp0noSTYcRtb4XDWc5J1L0vxRsvmPmrSUNLmYDrPz++G2HO+ZrJhjuCme8d6RRMpj5/k2TAnpx0PnjoLLnb9QLoe/U26CbmCQDTLSiXcC0g6jo3Wxyx37truWuG2M2Sh1vmV2qnJVi12FkOg6vJhtvIMvLU1M1kPCiAVcIGO9x4IU+tU/vV5LoNuuqEZT+fRJBtqbMH3LpRMRsMrB/ZRCJ2XnJIsRvkd6ibWYQkmk2L37R8OnNc7y7mI9N4iR158KPmcSL5Ft7LtV+J+42uAgWSolHlpvksBp3ZzIOMfofSRysr7vWmtqCK2U="
    on:
      all_branches: true
    #   branch: master
    #   tags: true
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/

  - provider: script
    script: maintenance/anaconda_deploy.sh
    on:
      all_branches: true
    #   branch: master
    #   tags: true

notifications:
  email: false
